name: example
description: Flutter Firebase Picture Uploader Example
version: 1.0.2

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.11.0"

dependencies:
  firebase_picture_uploader:
    path: ../

  flutter: 
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
 
flutter:
  uses-material-design: true
