name: firebase_picture_uploader
description: Picture upload widget which helps selecting and uploading one or multiple images to firebase storage.
version: 1.3.2
homepage: https://github.com/Rodiii/flutter_firebase_picture_uploader
maintainer: Christoph Rothermel (@rothech)

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.11.0"

dependencies:
  flutter:
    sdk: flutter
    
  cached_network_image: ^3.2.3
  firebase_storage: ^11.0.9
  firebase_core: ^2.4.0
  image: ^3.2.2 
  image_picker: ^0.8.6
  image_cropper: ^3.0.1
  shared_preferences: ^2.0.15
  path_provider: ^2.0.11
  cupertino_icons: ^1.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
 