name: firebase_picture_uploader
description: Picture upload widget which helps selecting and uploading one or multiple images to firebase storage.
version: 1.3.1
homepage: https://github.com/Rodiii/flutter_firebase_picture_uploader
maintainer: Christoph Rothermel (@rothech)

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  cached_network_image: ^3.1.0
  firebase_storage: ^10.0.4
  firebase_core: ^1.7.0
  image: ^3.0.8 
  image_picker: ^0.8.4+2
  image_cropper: ^1.4.1
  shared_preferences: ^2.0.8
  path_provider: ^2.0.5
  cupertino_icons: ^1.0.3 


dev_dependencies:
  flutter_test:
    sdk: flutter
 